web:
  build: .
  ports:
   - "8080:8080"
  environment:
   - SLIM_MODE=development
  links:
   - mysql
  volumes:
   - .:/app
  command: php -S 0.0.0.0:8080
mysql:
  image: tutum/mysql:5.6
  ports:
   - "3306:3306"
  environment:
   - DB_NAME=slimtodo
   - MYSQL_USER=mtgdbuser
   - MYSQL_PASS=mtgdb1
  volumes:
   - /var/lib/mysql:/var/lib/mysql
adminer:
  image: clue/adminer
  ports:
   - "3307:80"