web:
  build: .
  ports:
   - "8080:80"
  environment:
   - SLIM_MODE=development
  links:
   - mysql
  volumes:
   - .:/var/www/html
mysql:
  image: tutum/mysql:5.6
  ports:
   - "3306:3306"
  environment:
   - DB_NAME=todo
   - MYSQL_USER=todouser
   - MYSQL_PASS=todo1